// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Create a [AndroidNotificationChannel] for heads up notifications
 
  bool isFlutterLocalNotificationsInitialized = false;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMBndK3qWj1bg7M6Bbxqu7lRXHEcxZI-0',
    appId: '1:498627715273:android:ce935378e415049202ed18',
    messagingSenderId: '498627715273',
    projectId: 'harmoni-living',
    databaseURL: 'https://harmoni-living.firebaseio.com',
    storageBucket: 'harmoni-living.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfPh43MiEw9777mpDbHodWsl3zBCEliwI',
    appId: '1:498627715273:ios:c35765c1ca3ca61502ed18',
    messagingSenderId: '498627715273',
    projectId: 'harmoni-living',
    databaseURL: 'https://harmoni-living.firebaseio.com',
    storageBucket: 'harmoni-living.appspot.com',
    androidClientId: '498627715273-01s451i38k6taisb4mr6ph82rp70onmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.kumpulpay',
  );

  Future<void> setupFlutterNotifications() async {
    if (isFlutterLocalNotificationsInitialized) {
      return;
    }

    
    isFlutterLocalNotificationsInitialized = true;
  }
}
